name = "Simple Resume"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "//github.com/geoffsmiller/hugo-simple-resume/blob/master/LICENSE.md"
description = "A simple resume one-pager template based on digitalcraftsman's port of HTML5UP's Strata theme to Hugo"
homepage = "//github.com/geoffsmiller/hugo-simple-resume/"
tags = ["resume", "google analytics", "customizable", "single-page"]
features = ["", ""]
min_version = 0.16

[author]
  name = "digitalcraftsman"
  homepage = "//github.com/digitalcraftsman"

# If porting an existing theme
[original]
  name = "digitalcraftsman"
  homepage = "//github.com/digitalcraftsman"
  repo = "https://github.com/digitalcraftsman/hugo-strata-theme"
