baseurl = "https://your-base-url/"
languageCode = "en-us"
title = "Your Name – Job Title"
theme = "hugo-simple-resume"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""

[params]
	name = "Your Name"
	description = "Your Name's Resume"
	favicon = "favicon.ico"
	appletouchicon = "apple-touch-icon-precomposed.png"

	[params.sidebar]
		avatar = "avatar.jpg"
		bio = "Your Name"
		location = "Your City"
		email = "me@somewhere.com"
		wordpress = "with.ag"
		github = "geoffsmiller"
		linkedin = "geoffsmiller"
		twitter = "_withag"
		phone = "999-999-9999"
		pdf = "ExampleResume.pdf"

		copyright = [
			"&copy; Your Name",
			"Design: [HTML5 UP](//html5up.net)",
			"Image: [Noirlac](//noirlac.tumblr.com/post/149385419662)"
		]

	[params.about]
		hide  = false
		title = "Summary"
		content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus facilisis arcu sit amet bibendum efficitur. Nunc nec porta massa. Pellentesque eu aliquet ante. Aliquam neque sapien, imperdiet et turpis vitae, rhoncus ultrices erat. Integer a maximus massa, vulputate ornare ligula. Ut mollis elit risus, nec imperdiet lacus pretium a. Aliquam sed rhoncus mi, eget pellentesque tellus. Vestibulum venenatis dignissim condimentum. Sed sodales quam eu maximus aliquet. Nunc tellus nisl, mollis non fringilla eget, gravida consectetur orci. Sed eu faucibus metus, eu aliquam arcu."
	[params.skills]
		hide = false
		title = "Skills"

		[[params.skills.header]]
			text = "Sub-heading 1"

			[[params.skills.header.skill]]
				text = "Skill 1"

			[[params.skills.header.skill]]
				text = "Skill 2"

			[[params.skills.header.skill]]
				text = "Skill 3"

			[[params.skills.header.skill]]
				text = "Skill 4"

			[[params.skills.header.skill]]
				text = "Skill 5"

		[[params.skills.header]]
			text = "Sub-heading 2"

			[[params.skills.header.skill]]
				text = "Skill 6"

			[[params.skills.header.skill]]
				text = "Skill 7"

			[[params.skills.header.skill]]
				text = "Skill 8"

			[[params.skills.header.skill]]
				text = "Skill 9"

	[params.experience]
		hide = false
		title = "Experience"

		[[params.experience.job]]
			title = "Job Title 1"
			employer = "Employer 1"
			time_range = "Jan 2015–present"

			[[params.experience.job.bulletpoint]]
				text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

			[[params.experience.job.bulletpoint]]
				text = "Sed ornare magna sit amet facilisis posuere."

			[[params.experience.job.bulletpoint]]
				text = "Nullam ac turpis at mi finibus scelerisque sed in urna."

			[[params.experience.job.bulletpoint]]
				text = "Ut a elit et lectus iaculis consectetur."

			[[params.experience.job.bulletpoint]]
				text = "Curabitur at massa vel quam volutpat tincidunt."

			[[params.experience.job.bulletpoint]]
				text = "**_Sub-heading 1_**"

				[[params.experience.job.bulletpoint.subbulletpoint]]
					text = "In vitae lorem a est finibus vestibulum in ut sapien."

				[[params.experience.job.bulletpoint.subbulletpoint]]
					text = "Maecenas tristique sapien in elit porta consequat."

				[[params.experience.job.bulletpoint.subbulletpoint]]
					text = "Sed venenatis lorem id lectus dapibus ullamcorper ut vitae purus."

				[[params.experience.job.bulletpoint.subbulletpoint]]
					text = "In ut nibh id quam porttitor pretium."

			[[params.experience.job.bulletpoint]]
				text = "**_Sub-heading 2_**"

				[[params.experience.job.bulletpoint.subbulletpoint]]
					text = "Mauris dictum nisi id mauris venenatis, ut pulvinar libero elementum."

				[[params.experience.job.bulletpoint.subbulletpoint]]
					text = "Phasellus eleifend odio ut turpis auctor blandit."

				[[params.experience.job.bulletpoint.subbulletpoint]]
					text = "Cras nec arcu vitae libero tristique commodo."

		[[params.experience.job]]
			title = "Job Title 2"
			employer = "Employer 2"
			time_range = "Jan. 2010–Dec. 2014"

			[[params.experience.job.bulletpoint]]
				text = "Fusce non tellus ut libero fringilla interdum ut vel nibh."

			[[params.experience.job.bulletpoint]]
				text = "Mauris vestibulum dui et egestas lacinia."

			[[params.experience.job.bulletpoint]]
				text = "Nullam quis lacus consequat, venenatis dui vel, pretium metus."

			[[params.experience.job.bulletpoint]]
				text = "In nec orci id ipsum eleifend rutrum nec nec enim."

			[[params.experience.job.bulletpoint]]
				text = "Praesent finibus quam quis nisl posuere, et pellentesque erat fermentum."

			[[params.experience.job.bulletpoint]]
				text = "Cras vel libero vel urna fermentum suscipit quis vitae arcu."

	[params.education]
		hide = false
		title = "Education"

		[[params.education.school]]
			name = "School 1"
			time_range = "2010–2014"

			[[params.education.school.bulletpoint]]
				text = "Degree 1"

		[[params.education.school]]
			name = "School 2"
			time_range = "2000–2004"

			[[params.education.school.bulletpoint]]
				text = "Degree 2"
